[platformio]
description                 = Modbus RTU TCP gateway
src_dir                     = arduino-modbus-rtu-tcp-gateway
lib_dir                     = lib/default
;boards_dir                  = boards
build_cache_dir             = .cache

[env]
platform = atmelavr
framework = arduino
board = nanoatmega328

lib_deps = arduino-libraries/Ethernet@^2.0.2
           rlogiacco/CircularBuffer@^1.3.3
           jandrassy/StreamLib

[env:nanoatmega328new]
board = nanoatmega328new

[env:nanoatmega328]
board = nanoatmega328

[env:arduinouno]
board = uno

[env:dfr]
platform = atmelavr
framework = arduino
board = leonardoeth
upload_protocol = usbasp
upload_port = usb
upload_flags = -e
; https://embedds.com/all-you-need-to-know-about-avr-fuses/
board_fuses.lfuse = 0xFF
board_fuses.hfuse = 0xD9
board_fuses.efuse = 0xCB
board_fuses.lock_bits = 0x2F
board_fuses.unlock_bits = 0x3F
board_hardware.uart = no_bootloader
board_build.maximum_size = 32768
board_upload.maximum_size = 32768
